### ISSUE TITLE
Push actual source code to npm

### ISSUE THREAD

**Issue by deadcoder0904** [diracs-delta/gif-tsx#3]
As said [here](https://github.com/diracs-delta/gif.tsx-demo/issues/1#issuecomment-900816456), source code isn't being pushed to `npm` at all.

**Comment by dlqqq** [comment]
Hahaha what??? Damn it. That was my mistake, I forgot to run build before publish. Just switched to a new machine

**Comment by dlqqq** [comment]
Fixed in `0.1.5`. Added `yarn build` to `prepublishOnly` script so this won't happen again in the future. Hopefully.
